name: CI Pipeline

on:
  push:
    branches: [main, develop, 'feature/*']
  pull_request:
    branches: [main, develop]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Install dependencies
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: Install dependencies
        run: bun install
        
      # Code quality checks
      - name: Lint code with Biome
        run: bunx biome lint --apply-unsafe ./src
        
      - name: Format check
        run: bunx biome format --check ./src
        
      - name: Type check
        run: bun run type-check