name: CI Pipeline

on:
  push:
    branches: [main, develop, 'feature/*']
  pull_request:
    branches: [main, develop]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: Install dependencies
        run: bun install
        
      # Lint check
      - name: Run linter
        run: bun run lint
        
      # Format check
      - name: Check formatting
        run: bun run format:check
        
      # Type checking
      - name: Type check
        run: bun run type-check